"""Phase 1 domain model extension: household/consent fields on residents,
weight/condition on bags, image provenance on captures, richer OCR/state
fields on detections, a category tree + sensitivity flags on vocabulary,
and new tables for pickup scheduling, field staff, inspection stations,
bins, per-attempt vision-model inference runs, bank details, an unmapped-
label queue, and calendar reference data.

Autogenerated via `alembic revision --autogenerate`, then hand-reviewed and
rewritten to match this project's migration conventions: named enum types
created once via the `_ENUMS` pattern (see 0001), `postgresql.UUID(as_uuid=True)`
instead of the generic `sa.UUID()`, and — the part autogenerate cannot know
to do — explicit `server_default` added to every NOT NULL column on an
*existing* table (and, for consistency with 0001, on new tables too) so
these ALTER TABLEs don't fail against the rows already in `users`,
`detections`, and `item_vocabulary`. See DECISIONS.md.

Revision ID: 0002
Revises: 0001
Create Date: 2026-08-23
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# create_type=False on every one of these, matching 0001's pattern: each is
# created exactly once, explicitly, by the loop at the top of upgrade() —
# not implicitly when first referenced in a Column. Without create_type=False
# here, op.create_table()/op.add_column() would *also* try to CREATE TYPE
# for these on first use and collide with that explicit loop.
building_type = postgresql.ENUM(
    "HOUSE", "ANNEX", "APARTMENT", name="building_type", create_type=False
)
price_tier = postgresql.ENUM("ECONOMY", "MID", "PREMIUM", name="price_tier", create_type=False)
diet_profile = postgresql.ENUM(
    "MIXED", "VEGETARIAN", "SEAFOOD", "MEAT", name="diet_profile", create_type=False
)
resident_status = postgresql.ENUM(
    "ACTIVE", "INACTIVE", "SUSPENDED", name="resident_status", create_type=False
)
preferred_language = postgresql.ENUM("si", "ta", "en", name="preferred_language", create_type=False)
bag_condition = postgresql.ENUM(
    "GOOD", "WET", "TORN", "OVERFILLED", name="bag_condition", create_type=False
)
lighting_condition = postgresql.ENUM(
    "OVERHEAD_LED", "MIXED_DAYLIGHT", name="lighting_condition", create_type=False
)
item_state = postgresql.ENUM(
    "FRESH_TRIM",
    "RIPE",
    "OVERRIPE",
    "SPOILED",
    "MOULDY",
    name="item_state",
    create_type=False,
)
pickup_channel = postgresql.ENUM(
    "MOBILE_APP", "WHATSAPP", "IVR", "PHONE", name="pickup_channel", create_type=False
)
pickup_status = postgresql.ENUM(
    "REQUESTED", "COMPLETED", "CANCELLED", "MISSED", name="pickup_status", create_type=False
)
inference_run_status = postgresql.ENUM(
    "SUCCESS",
    "FAILED_INVALID_JSON",
    "FAILED_PROVIDER_ERROR",
    "TIMEOUT",
    name="inference_run_status",
    create_type=False,
)
bin_type = postgresql.ENUM(
    "ORGANIC", "PAPER", "POLYTHENE", "GENERAL", name="bin_type", create_type=False
)

_ENUMS = (
    building_type,
    price_tier,
    diet_profile,
    resident_status,
    preferred_language,
    bag_condition,
    lighting_condition,
    item_state,
    pickup_channel,
    pickup_status,
    inference_run_status,
    bin_type,
)

# Reused (already-created, from 0001) enum, referenced with create_type=False
# everywhere it's used below.
_bag_type_ref = postgresql.ENUM(
    "organic", "polythene", "paper", "general", name="bag_type", create_type=False
)


def upgrade() -> None:
    bind = op.get_bind()
    for e in _ENUMS:
        e.create(bind, checkfirst=True)

    # --- New tables, in FK-dependency order ---

    op.create_table(
        "bins",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("bin_code", sa.String(50), nullable=False, unique=True),
        sa.Column("bin_type", bin_type, nullable=False),
        sa.Column("location", sa.String(200), nullable=True),
        sa.Column("capacity_kg", sa.Numeric(10, 2), nullable=True),
        sa.Column("downstream_process", sa.String(200), nullable=True),
        sa.Column("vendor_name", sa.String(200), nullable=True),
    )

    op.create_table(
        "calendar_days",
        sa.Column("calendar_date", sa.Date(), primary_key=True),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("is_weekend", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_poya", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_public_holiday", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("note", sa.String(200), nullable=True),
    )

    op.create_table(
        "inspection_stations",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("station_code", sa.String(50), nullable=False, unique=True),
        sa.Column("facility_name", sa.String(200), nullable=False),
        sa.Column("line_name", sa.String(100), nullable=True),
        sa.Column("camera_identifier", sa.String(100), nullable=True),
        sa.Column(
            "default_lighting",
            postgresql.ENUM(
                "OVERHEAD_LED", "MIXED_DAYLIGHT", name="lighting_condition", create_type=False
            ),
            nullable=True,
        ),
    )

    op.create_table(
        "collectors",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "staff_account_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("staff_accounts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("employee_code", sa.String(50), nullable=False, unique=True),
        sa.Column("full_name", sa.String(200), nullable=False),
        sa.Column("phone", sa.String(20), nullable=True),
        sa.Column("default_vehicle_code", sa.String(50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    op.create_index(
        "ix_collectors_staff_account_id", "collectors", ["staff_account_id"], unique=True
    )

    op.create_table(
        "resident_bank_details",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "resident_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("account_holder_name", sa.String(200), nullable=True),
        sa.Column("bank_name", sa.String(200), nullable=True),
        sa.Column("branch", sa.String(200), nullable=True),
        sa.Column("account_number_encrypted", sa.Text(), nullable=True),
        sa.Column("account_last4", sa.String(4), nullable=True),
        sa.Column("is_verified", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
    )
    op.create_index(
        "ix_resident_bank_details_resident_id",
        "resident_bank_details",
        ["resident_id"],
        unique=True,
    )

    op.create_table(
        "unmapped_labels",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("raw_label", sa.String(200), nullable=False),
        sa.Column("bag_type", _bag_type_ref, nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False, server_default="1"),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column(
            "suggested_vocabulary_item_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("item_vocabulary.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("resolved", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.UniqueConstraint("raw_label", "bag_type", name="uq_unmapped_label_bagtype"),
    )
    op.create_index("ix_unmapped_labels_bag_type", "unmapped_labels", ["bag_type"])

    op.create_table(
        "bin_transfers",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "bag_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("bags.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("from_tray_code", sa.String(50), nullable=True),
        sa.Column(
            "bin_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("bins.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "transferred_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "operator_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("staff_accounts.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("weight_kg", sa.Numeric(8, 2), nullable=True),
    )
    op.create_index("ix_bin_transfers_bag_id", "bin_transfers", ["bag_id"])
    op.create_index("ix_bin_transfers_bin_id", "bin_transfers", ["bin_id"])

    op.create_table(
        "pickup_requests",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "resident_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("requested_for_date", sa.Date(), nullable=False),
        sa.Column("requested_window", sa.String(50), nullable=True),
        sa.Column(
            "requested_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("channel", pickup_channel, nullable=False),
        sa.Column("declared_bag_count", sa.Integer(), nullable=True),
        sa.Column("status", pickup_status, nullable=False, server_default="REQUESTED"),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column(
            "collection_session_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("collection_sessions.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    op.create_index("ix_pickup_requests_resident_id", "pickup_requests", ["resident_id"])
    op.create_index(
        "ix_pickup_requests_date_status", "pickup_requests", ["requested_for_date", "status"]
    )

    op.create_table(
        "inference_runs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "capture_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("captures.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("provider_name", sa.String(50), nullable=False),
        sa.Column("model_name", sa.String(200), nullable=False),
        sa.Column("model_version", sa.String(100), nullable=True),
        sa.Column("prompt_version", sa.String(50), nullable=True),
        sa.Column("status", inference_run_status, nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=True),
        sa.Column("output_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Numeric(12, 6), nullable=True),
        sa.Column("overall_confidence", sa.Float(), nullable=True),
        sa.Column("model_predicted_bag_type", _bag_type_ref, nullable=True),
        sa.Column("raw_response", postgresql.JSONB(), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.UniqueConstraint("capture_id", "attempt_no", name="uq_inference_run_capture_attempt"),
    )
    op.create_index("ix_inference_runs_capture_id", "inference_runs", ["capture_id"])
    op.create_index("ix_inference_runs_status", "inference_runs", ["status"])
    op.create_index("ix_inference_runs_model_name", "inference_runs", ["model_name"])

    # --- Extend existing tables ---

    op.add_column("bags", sa.Column("gross_weight_kg", sa.Numeric(8, 2), nullable=True))
    op.add_column("bags", sa.Column("tare_weight_kg", sa.Numeric(8, 2), nullable=True))
    op.add_column("bags", sa.Column("bag_condition", bag_condition, nullable=True))
    op.add_column(
        "bags",
        sa.Column(
            "assigned_bin_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("bins.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )

    op.add_column(
        "captures",
        sa.Column(
            "inspection_station_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("inspection_stations.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    op.add_column("captures", sa.Column("tray_code", sa.String(50), nullable=True))
    op.add_column("captures", sa.Column("image_sha256", sa.String(64), nullable=True))
    op.add_column("captures", sa.Column("image_width", sa.Integer(), nullable=True))
    op.add_column("captures", sa.Column("image_height", sa.Integer(), nullable=True))
    op.add_column("captures", sa.Column("file_size_bytes", sa.Integer(), nullable=True))
    op.add_column("captures", sa.Column("lighting_condition", lighting_condition, nullable=True))
    op.create_index("ix_captures_bag_captured", "captures", ["bag_id", "captured_at"])
    op.create_unique_constraint(
        "uq_captures_bag_image_sha256", "captures", ["bag_id", "image_sha256"]
    )

    op.add_column(
        "collection_sessions",
        sa.Column(
            "collector_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("collectors.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    op.add_column("collection_sessions", sa.Column("vehicle_code", sa.String(50), nullable=True))
    op.add_column("collection_sessions", sa.Column("route_code", sa.String(50), nullable=True))
    op.add_column("collection_sessions", sa.Column("gps_latitude", sa.Numeric(9, 6), nullable=True))
    op.add_column(
        "collection_sessions", sa.Column("gps_longitude", sa.Numeric(9, 6), nullable=True)
    )
    op.add_column(
        "collection_sessions",
        sa.Column("warehouse_arrival_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("collection_sessions", sa.Column("notes", sa.Text(), nullable=True))
    op.create_index(
        "ix_collection_sessions_user_collected", "collection_sessions", ["user_id", "collected_at"]
    )

    op.add_column("detections", sa.Column("brand_text", sa.Text(), nullable=True))
    op.add_column("detections", sa.Column("product_name_text", sa.Text(), nullable=True))
    op.add_column("detections", sa.Column("pack_size_text", sa.Text(), nullable=True))
    op.add_column("detections", sa.Column("barcode_text", sa.Text(), nullable=True))
    op.add_column("detections", sa.Column("item_state", item_state, nullable=True))
    op.add_column(
        "detections",
        sa.Column("is_contaminant", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column("detections", sa.Column("estimated_weight_g", sa.Numeric(10, 2), nullable=True))
    op.add_column("detections", sa.Column("count_est", sa.Integer(), nullable=True))
    op.add_column("detections", sa.Column("bbox_x", sa.Integer(), nullable=True))
    op.add_column("detections", sa.Column("bbox_y", sa.Integer(), nullable=True))
    op.add_column("detections", sa.Column("bbox_w", sa.Integer(), nullable=True))
    op.add_column("detections", sa.Column("bbox_h", sa.Integer(), nullable=True))
    op.add_column(
        "detections",
        sa.Column(
            "inference_run_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("inference_runs.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    op.create_index("ix_detections_brand_text", "detections", ["brand_text"])
    op.create_index("ix_detections_item_state", "detections", ["item_state"])
    op.create_index("ix_detections_is_contaminant", "detections", ["is_contaminant"])
    op.create_index("ix_detections_inference_run_id", "detections", ["inference_run_id"])

    op.add_column(
        "item_vocabulary",
        sa.Column(
            "parent_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("item_vocabulary.id", ondelete="SET NULL"),
            nullable=True,
        ),
    )
    op.add_column(
        "item_vocabulary",
        sa.Column(
            "is_contaminant_by_default", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
    )
    op.add_column(
        "item_vocabulary",
        sa.Column("is_sensitive", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index("ix_item_vocabulary_parent_id", "item_vocabulary", ["parent_id"])

    op.add_column("users", sa.Column("zone_code", sa.String(20), nullable=True))
    op.add_column("users", sa.Column("building_type", building_type, nullable=True))
    op.add_column("users", sa.Column("declared_household_size", sa.Integer(), nullable=True))
    op.add_column("users", sa.Column("registered_date", sa.Date(), nullable=True))
    op.add_column("users", sa.Column("qr_code", sa.String(64), nullable=True))
    op.add_column("users", sa.Column("preferred_language", preferred_language, nullable=True))
    op.add_column("users", sa.Column("price_tier", price_tier, nullable=True))
    op.add_column("users", sa.Column("diet_profile", diet_profile, nullable=True))
    op.add_column(
        "users",
        sa.Column("consent_operational", sa.Boolean(), nullable=False, server_default=sa.true()),
    )
    # Opt-in, never opt-out: existing residents get FALSE, not backfilled to
    # true. See DECISIONS.md.
    op.add_column(
        "users",
        sa.Column("consent_profiling", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "users", sa.Column("consent_captured_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users", sa.Column("status", resident_status, nullable=False, server_default="ACTIVE")
    )
    op.create_index("ix_users_zone_code", "users", ["zone_code"])
    op.create_unique_constraint("uq_users_qr_code", "users", ["qr_code"])


def downgrade() -> None:
    op.drop_constraint("uq_users_qr_code", "users", type_="unique")
    op.drop_index("ix_users_zone_code", table_name="users")
    for col in (
        "status",
        "consent_captured_at",
        "consent_profiling",
        "consent_operational",
        "diet_profile",
        "price_tier",
        "preferred_language",
        "qr_code",
        "registered_date",
        "declared_household_size",
        "building_type",
        "zone_code",
    ):
        op.drop_column("users", col)

    op.drop_index("ix_item_vocabulary_parent_id", table_name="item_vocabulary")
    for col in ("is_sensitive", "is_contaminant_by_default", "parent_id"):
        op.drop_column("item_vocabulary", col)

    op.drop_index("ix_detections_inference_run_id", table_name="detections")
    op.drop_index("ix_detections_is_contaminant", table_name="detections")
    op.drop_index("ix_detections_item_state", table_name="detections")
    op.drop_index("ix_detections_brand_text", table_name="detections")
    for col in (
        "inference_run_id",
        "bbox_h",
        "bbox_w",
        "bbox_y",
        "bbox_x",
        "count_est",
        "estimated_weight_g",
        "is_contaminant",
        "item_state",
        "barcode_text",
        "pack_size_text",
        "product_name_text",
        "brand_text",
    ):
        op.drop_column("detections", col)

    op.drop_index("ix_collection_sessions_user_collected", table_name="collection_sessions")
    for col in (
        "notes",
        "warehouse_arrival_at",
        "gps_longitude",
        "gps_latitude",
        "route_code",
        "vehicle_code",
        "collector_id",
    ):
        op.drop_column("collection_sessions", col)

    op.drop_constraint("uq_captures_bag_image_sha256", "captures", type_="unique")
    op.drop_index("ix_captures_bag_captured", table_name="captures")
    for col in (
        "lighting_condition",
        "file_size_bytes",
        "image_height",
        "image_width",
        "image_sha256",
        "tray_code",
        "inspection_station_id",
    ):
        op.drop_column("captures", col)

    for col in ("assigned_bin_id", "bag_condition", "tare_weight_kg", "gross_weight_kg"):
        op.drop_column("bags", col)

    op.drop_index("ix_inference_runs_model_name", table_name="inference_runs")
    op.drop_index("ix_inference_runs_status", table_name="inference_runs")
    op.drop_index("ix_inference_runs_capture_id", table_name="inference_runs")
    op.drop_table("inference_runs")

    op.drop_index("ix_pickup_requests_date_status", table_name="pickup_requests")
    op.drop_index("ix_pickup_requests_resident_id", table_name="pickup_requests")
    op.drop_table("pickup_requests")

    op.drop_index("ix_bin_transfers_bin_id", table_name="bin_transfers")
    op.drop_index("ix_bin_transfers_bag_id", table_name="bin_transfers")
    op.drop_table("bin_transfers")

    op.drop_index("ix_unmapped_labels_bag_type", table_name="unmapped_labels")
    op.drop_table("unmapped_labels")

    op.drop_index("ix_resident_bank_details_resident_id", table_name="resident_bank_details")
    op.drop_table("resident_bank_details")

    op.drop_index("ix_collectors_staff_account_id", table_name="collectors")
    op.drop_table("collectors")

    op.drop_table("inspection_stations")
    op.drop_table("calendar_days")
    op.drop_table("bins")

    bind = op.get_bind()
    for e in _ENUMS:
        e.drop(bind, checkfirst=True)
