"""Phase 3 review workflow: the human_reviews table (one row per reviewer
decision on a Detection) and its review_verdict enum.

Autogenerated then hand-reviewed to match this project's migration
conventions (named enum via the _ENUMS pattern, postgresql.UUID(as_uuid=True),
explicit index names) — same treatment as 0002/0003. No backfill: this is a
brand-new table with no prior data to reconcile.

Revision ID: 0004
Revises: 0003
Create Date: 2026-08-24
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

review_verdict = postgresql.ENUM(
    "CONFIRMED", "CORRECTED", "REJECTED", name="review_verdict", create_type=False
)
_ENUMS = (review_verdict,)


def upgrade() -> None:
    bind = op.get_bind()
    for e in _ENUMS:
        e.create(bind, checkfirst=True)

    op.create_table(
        "human_reviews",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column(
            "detection_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("detections.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "reviewer_id",
            postgresql.UUID(as_uuid=True),
            sa.ForeignKey("staff_accounts.id", ondelete="RESTRICT"),
            nullable=False,
        ),
        sa.Column(
            "reviewed_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False
        ),
        sa.Column("verdict", review_verdict, nullable=False),
        sa.Column("corrected_item_name", sa.String(100), nullable=True),
        sa.Column("corrected_brand_text", sa.Text(), nullable=True),
        sa.Column("corrected_count", sa.Integer(), nullable=True),
        sa.Column("corrected_is_contaminant", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("time_spent_seconds", sa.Integer(), nullable=True),
    )
    op.create_index("ix_human_reviews_detection_id", "human_reviews", ["detection_id"])
    op.create_index("ix_human_reviews_reviewer_id", "human_reviews", ["reviewer_id"])
    op.create_index("ix_human_reviews_verdict", "human_reviews", ["verdict"])


def downgrade() -> None:
    op.drop_index("ix_human_reviews_verdict", table_name="human_reviews")
    op.drop_index("ix_human_reviews_reviewer_id", table_name="human_reviews")
    op.drop_index("ix_human_reviews_detection_id", table_name="human_reviews")
    op.drop_table("human_reviews")

    bind = op.get_bind()
    for e in _ENUMS:
        e.drop(bind, checkfirst=True)
